### ISSUE TITLE
comparison with `obsidian` plugins

### ISSUE THREAD

**Issue by benrbray** [benrbray/noteworthy#52]
While designing Noteworthy's extension system / extension API, it will be useful to compare with Obsidian's existing plugins.  

* [x] plugins with a checkmark are already possible with Noteworthy's extension API
* [ ] plugins without a checkmark are not currently possible to build with Noteworthy's extension API

### Math Plugins

* [ ] [`obsidian-latex-suite`](https://github.com/artisticat1/obsidian-latex-suite)
* [ ] [`obsidian-mathlinks`](https://github.com/zhaoshenzhai/obsidian-mathlinks)
* [ ] [`obsidian-mathjax-wikilinks`](https://github.com/aaron-jack-manning/obsidian-mathjax-wikilinks)
* [ ] [`obsidian-matrix`](https://github.com/MohrJonas/obsidian-matrix)
* [x] [`obsidian-asciimath`](https://github.com/widcardw/obsidian-asciimath)
* [ ] [`obsidian-mathpad`](https://github.com/Canna71/obsidian-mathpad)
* [ ] [`obsidian-math-plus`](https://github.com/ocapraro/obsidian-math-plus)

### LaTeX Plugins

I've confirmed that the following are subsumed by noteworthy's `tikzjax` plugin:

* [x] [`obsidian-tikzjax`](https://github.com/artisticat1/obsidian-tikzjax) (added by #36)

The following are most likely possible with the noteworthy `tikzjax` plugin, but I haven't attempted it:

* [x] [`obsidian-latex-algorithms`](https://github.com/SamZhang02/obsidian-latex-algorithms)

The following are not currently possible:

* [ ] [`obsidian-latex`](https://github.com/wei2912/obsidian-latex) (depends on #50)

### Code Block Plugins

* [ ] [`obsidian-code-emitter`](https://github.com/mokeyish/obsidian-code-emitter)
* [ ] [`obsidian-code-preview`](https://github.com/zjhcn/obsidian-code-preview)

### Diagram Plugins

* [x] [`obsidian-functionplot`](https://github.com/leonhma/obsidian-functionplot)
* [x] [`obsidian-graphviz`](https://github.com/QAMichaelPeng/obsidian-graphviz) (depends on #50)
* [x] [`obsidian-argdown-plugin`](https://github.com/amdecker/obsidian-argdown-plugin)
* [x] [`obsidian-dilogue-plugin`](https://github.com/holubj/obsidian-dialogue-plugin)
* [x] [`obsidian-plugin-abcjs`](https://github.com/abcjs-music/obsidian-plugin-abcjs)
* [x] [`d2-obsidian`](https://github.com/terrastruct/d2-obsidian)
* [x] [`obsidian-numerals`](https://github.com/gtg922r/obsidian-numerals)
* [x] [`obsidian-chat-view`](https://github.com/adifyr/obsidian-chat-view)
* [ ] [`obsidian-circuitjs`](https://github.com/StevenGann/obsidian-circuitjs)
* [ ] [`scales-chords`](https://github.com/egradman/scales-chords) (depends on #51)

### File Type Plugins

* [ ] [`obsidian-literate-haskell`](https://github.com/jajaperson/obsidian-literate-haskell)
* [ ] [`obsidian-markdown-file-suffix`](https://github.com/git-no/obsidian-markdown-file-suffix)
* [ ] [`obsidian-txt-as-md`](https://github.com/deathau/txt-as-md-obsidian)

### Citation Plugins

* [ ] [`obsidian-zotero-integration`](https://github.com/mgmeyers/obsidian-zotero-integration)
* [ ] [`obsidian-citation-plugin`](https://github.com/hans/obsidian-citation-plugin)
* [ ] [`obsidian-pandoc-reference-list`](https://github.com/mgmeyers/obsidian-pandoc-reference-list)
* [ ] [`zotero-bridge`](https://github.com/vanakat/zotero-bridge)

### Note Organization Plugins

* [ ] [`obsidian-create-note-in-folder`](https://github.com/Lisandra-dev/obsidian-create-note-in-folder)
* [ ] [`obsidian-rapid-notes`](https://github.com/valteriomon/obsidian-rapid-notes)
* [ ] [`note-refactor-obsidian`](https://github.com/lynchjames/note-refactor-obsidian)
* [ ] [`obsidian-tagfolder`](https://github.com/vrtmrz/obsidian-tagfolder)
* [ ] [`obsidian-folder-notes`](https://github.com/LostPaul/obsidian-folder-notes)
* [ ] [`obsidian-note-from-template`](https://github.com/mo-seph/obsidian-note-from-template)

### Theme Plugins

* [ ] [`obsidian-colorful-note-borders`](https://github.com/rusi/obsidian-colorful-note-borders)
* [ ] [`obsidian-style-settings`](https://github.com/mgmeyers/obsidian-style-settings)
* [ ] [`obsidian-file-color`](https://github.com/ecustic/obsidian-file-color)
* [ ] [`obsidian-theme-design-utilities`](https://github.com/chrisgrieser/obsidian-theme-design-utilities)
* [ ] [`obsidian-icon-folder`](https://github.com/FlorianWoelki/obsidian-icon-folder)

### Editor Plugins

* [ ] [`obsidian-block-drag-n-drop`](https://github.com/artem-barmin/obsidian-block-drag-n-drop)
* [ ] [`obsidian-image-caption`](https://github.com/alangrainger/obsidian-image-captions)
* [ ] [`obsidian-plugin-toc`](https://github.com/hipstersmoothie/obsidian-plugin-toc)
* [ ] [`better-fn`](https://github.com/aidenlx/better-fn) footnote hover

### Syntax Plugins

* [ ] [`markdown-attributes`](https://github.com/javalent/markdown-attributes)
* [ ] [`obsidian-list-callouts`](https://github.com/mgmeyers/obsidian-list-callouts)

### HTML Output Plugins

* [ ] [`obsidian-custom-classes`](https://github.com/LilaRest/obsidian-custom-classes)

### Metadata Plugins

* [ ] [`tag-wrangler`](https://github.com/pjeby/tag-wrangler)
* [ ] [`metaedit`](https://github.com/chhoumann/MetaEdit)

### Import Plugins

* [ ] [`obsidian-extract-url`](https://github.com/trashhalo/obsidian-extract-url)

### Export Plugins

* [ ] [`obsidian-save-as-gist`](https://github.com/ghedamat/obsidian-save-as-gist)
* [ ] [`obsidian-to-anki`](https://github.com/Pseudonium/Obsidian_to_Anki)

### Language Support Plugins

* [ ] [`obsidian-markdown-furigana`](https://github.com/steven-kraft/obsidian-markdown-furigana)
* [ ] [`obsidian-furigana`](https://github.com/uonr/obsidian-furigana)
* [ ] [`cm-japanese-patch`](https://github.com/sonarAIT/cm-japanese-patch)

### Todo Plugins

* [ ] [`obsidian-reminder`](https://github.com/uphy/obsidian-reminder)

### Miscellaneous

* [ ] [`obsidian-rss`](https://github.com/joethei/obsidian-rss) (depends on #51)
* [ ] [`obsidian-notion-like-tables`](https://github.com/trey-wallis/obsidian-notion-like-tables)
* [ ] [`obsidian-creases`](https://github.com/liamcain/obsidian-creases)
* [ ] [`obsidian-gallery`](https://github.com/Darakah/obsidian-gallery)
* [ ] [`obsidian-frontmatter-tag-suggest`](https://github.com/jmilldotdev/obsidian-frontmatter-tag-suggest)
* [ ] [`obsidian-hover-external-link`](https://github.com/jamiebrynes7/obsidian-hover-external-link)
* [ ] [`obsidian-frontmatter-links`](https://github.com/Trikzon/obsidian-frontmatter-links)
* [ ] [`obsidian-frontmatter-title`](https://github.com/snezhig/obsidian-front-matter-title)
